<a href="https://colab.research.google.com/github/luisaorcales113-design/luisaaliana/blob/main/Week_2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Business analytics - Fall 2026
Instructor: Dr. Ilia Tetin


<img src="https://raw.githubusercontent.com/dvgodoy/PyTorch101_ODSC_Europe2020/master/images/linear_dogs.jpg" alt="Linear regression example with dogs" height="200" width="800">


In [2]:
import numpy as np

## Why Do We Need This Package?

`numpy` is a library that allows for convenient work with multidimensional arrays and matrices and includes mathematical functions. Additionally, `numpy` enables vectorization of many computations and is useful in data analysis.



In [1]:
x = [1, 2, 3]
y = [4, 5, 6]

print(x + y)  # lists are concatenated
print(3 * x)  # the list is repeated three times
type(x)
# Output: <class 'list'>

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


list

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)  # element-wise addition with numpy
print(3 * x)  # each element is multiplied by the number
type(x)
# Output: <class 'numpy.ndarray'>


[5 7 9]
[3 6 9]


numpy.ndarray

In [4]:
x = np.arange(10**7)
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y = x.tolist()  # Convert to a list of Python integers for the comparison
y[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
%%timeit
sum(y)

146 ms ± 20.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%%timeit
np.sum(x)

8.2 ms ± 716 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


NumPy operates quickly for several reasons:
* Numeric arrays store fixed-size elements of one dtype in a memory buffer. Many arrays are contiguous, but slices and transposes can be non-contiguous views.
* Vectorized operations run compiled loops, avoiding Python-level iteration.
* Matrix operations can use optimized linear algebra libraries such as BLAS.

# 1. Vectors and Matrices

Let's take a closer look at the basics of working with matrices and vectors!

## 1.1 Vectors
Basic arithmetic operations work element-wise in a vectorized manner. Operations such as `@` and reductions such as `sum` have different meanings.


In [8]:
x = np.array([1, -10, 3, 0, 1, 75, 3])
x[3:6]

array([ 0,  1, 75])

In [9]:
x[x > 0]

array([ 1,  3,  1, 75,  3])

In [10]:
x[(x > 0) & (x <= 70)]

array([1, 3, 1, 3])

In [11]:
x[[2, 5]]

array([ 3, 75])

There are many ways to create a vector in `numpy`. You can do this by listing the elements, as was done earlier for the vector `x`. However, you can also use various special functions.


In [12]:
y = np.arange(start=10, stop=20, step=2)  # The last value is not included!
y

array([10, 12, 14, 16, 18])

In [13]:
y = np.ones(5)  # A vector of length 5 filled with ones
y

array([1., 1., 1., 1., 1.])

In [14]:
y = np.zeros(4)  # A vector of length 4 filled with zeros
y

array([0., 0., 0., 0.])

In [15]:
y = np.random.rand(5)  # A random vector, uniformly distributed on [0, 1)
y

array([0.32450742, 0.3420797 , 0.93585022, 0.20734482, 0.95584065])

In [16]:
y = np.ones_like(x)  # A vector of ones with the same length as vector x
y

array([1, 1, 1, 1, 1, 1, 1])

Essentially, a vector in numpy is a one-dimensional array, which corresponds to the intuitive definition of a vector:

In [17]:
y.shape  # Shape: one axis of length 7; y.ndim is 1

(7,)

For more detailed information on how to create vectors in NumPy, see the [documentation](https://numpy.org/doc/stable/user/basics.creation.html).

## 1.2 Matrices

You can also create a matrix!


In [18]:
A = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
A

array([[1, 2, 3],
       [2, 5, 6],
       [6, 7, 4]])

In [19]:
A.shape  # Dimensions of the matrix

(3, 3)

In [20]:
A[2]    # The third row of the matrix

array([6, 7, 4])

In [21]:
A[:,1]  # The second column of the matrix

array([2, 5, 7])

In [22]:
A[2][1] # Indexing first by row, then by column

np.int64(7)

In [23]:
A[2,1]  # Or indexing both dimensions at once

np.int64(7)

In [24]:
A[1:,1:] # You can create slices

array([[5, 6],
       [7, 4]])

For more detailed information on various ways of indexing arrays, see the [documentation](https://numpy.org/doc/stable/user/basics.indexing.html).

### Boolean arrays
Boolean arrays allow you to retrieve elements at positions where there is `True` in the boolean array (the expression in square brackets):

In [25]:
is_even = A % 2 == 0  # Check for even elements
print(is_even)

A[is_even]

[[False  True False]
 [ True False  True]
 [ True False  True]]


array([2, 2, 6, 6, 4])

In [26]:
np.where(A % 2 == 0)  # Returns the indices of even elements (row and column numbers)
idx = np.where(A % 2 == 0)
print(A)
print(idx)
A[idx]

[[1 2 3]
 [2 5 6]
 [6 7 4]]
(array([0, 1, 1, 2, 2]), array([1, 0, 2, 0, 2]))


array([2, 2, 6, 6, 4])

### Special Matrices
You can create special matrices using various functions, similarly to how you create vectors.

In [27]:
np.ones((3, 3))  # 3x3 matrix filled with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.zeros((3, 3))  # 3x3 matrix filled with zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.random.normal(size=(3, 3))  # 3x3 matrix with normally distributed random values

array([[-0.50780465, -0.8802079 , -0.22103353],
       [ 0.94469041, -1.74354896,  1.16715182],
       [ 1.88874595,  1.1209209 ,  1.00960635]])

In [30]:
np.eye(5)  # 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Reshaping Arrays
You can change the dimensions of arrays, provided that the number of elements allows for it.

In [31]:
v = np.arange(0, 24, 2)
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [32]:
v.shape  # Current shape

(12,)

In [33]:
v.reshape((3, 4))  # Reshape to 3x4

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [34]:
# A 12-element array cannot be reshaped into 18 elements.
# Catch the expected error so Run All can continue.
try:
    v.reshape((3, 6))
except ValueError as error:
    print(f"Expected ValueError: {error}")


Expected ValueError: cannot reshape array of size 12 into shape (3,6)


In [35]:
v.reshape((3, -1)) # -1 => automatically determine the size of the second dimension

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [36]:
D = np.random.normal(size=(3, 3, 3))  # 3x3x3 array (a vector of matrices)
D.shape  # Dimensions of D


(3, 3, 3)

In [37]:
D # Display the 3D array

array([[[ 1.19746895, -0.33051396, -0.00436394],
        [ 0.81392377,  2.69095628,  2.08138794],
        [-1.5570216 , -1.01396288,  0.87588553]],

       [[-0.98502945, -0.50063725, -0.45210239],
        [ 0.61787236, -0.8341994 ,  0.49436588],
        [-0.14159194, -1.98691699,  2.59669119]],

       [[-0.1985905 , -0.36847641,  1.63349804],
        [-0.03558156,  0.50679321,  0.18003632],
        [-0.54493729, -0.16583557,  0.7448125 ]]])

Arrays can be combined:



In [38]:
A = np.array([[1, 2], [3, 4]])

In [39]:
# Horizontal Stack. Combines arrays horizontally (column-wise):
np.hstack((A, np.zeros(A.shape)))

array([[1., 2., 0., 0.],
       [3., 4., 0., 0.]])

In [40]:
# Vertical Stack. Combines arrays vertically (row-wise)
np.vstack((A, np.zeros(A.shape)))

array([[1., 2.],
       [3., 4.],
       [0., 0.],
       [0., 0.]])

In [41]:
# Concatenate Combines arrays along a specified axis:
np.concatenate((A, np.eye(A.shape[1])), axis=0)

array([[1., 2.],
       [3., 4.],
       [1., 0.],
       [0., 1.]])

For more detailed information on how to create arrays in numpy, see the [documentation](https://numpy.org/doc/stable/user/basics.creation.html).

## 1.3 Vectors, Row Vectors, and Column Vectors



In [42]:
a = np.array([1, 2, 3])  # Vector (1D array)

In [43]:
b = np.array([[1], [2], [3]]) # Column vector (2D array)

In [44]:
a.shape

(3,)

In [45]:
b.shape

(3, 1)

Note: A vector (1D array) and a column vector or row vector (2D arrays) are different objects in numpy, although mathematically they represent the same entity. For a 1D array, the shape tuple consists of a single number and looks like `(n,)`, where `n` is the length of the vector. In the case of 2D vectors, the shape contains an additional dimension equal to one.

Shape matters: a 1D array has no row or column orientation. For example, adding arrays of shapes `(3,)` and `(3, 1)` broadcasts to `(3, 3)`. Use `reshape` or `np.newaxis` when you need a specific orientation. Transposing a 1D array leaves its shape unchanged:

In [46]:
a.T  # Transposing a 1D array does not change it

array([1, 2, 3])

In [47]:
b.T  # Transposing a column vector

array([[1, 2, 3]])

### 1.4 Matrix and Column Vector Multiplication
Matrices can be multiplied!

In [48]:
A = np.array([[1, 0], [0, 1]])
B = np.array([[4, 1], [2, 2]])
A@B

array([[4, 1],
       [2, 2]])

In [49]:
np.dot(A, B)

array([[4, 1],
       [2, 2]])

In [50]:
x = np.array([1, 2])
B@x

array([6, 6])

__Note:__ The operation __`*`__ performs element-wise multiplication on matrices, not matrix multiplication!

In [51]:
A * B

array([[4, 0],
       [0, 2]])

Basic arithmetic operations on arrays are performed element-wise.

In [52]:
A + B

array([[5, 1],
       [2, 3]])

In [53]:
A * 1.0 / B

array([[0.25, 0.  ],
       [0.  , 0.5 ]])

In [54]:
A + 1

array([[2, 1],
       [1, 2]])

In [55]:
3 * A

array([[3, 0],
       [0, 3]])

In [56]:
A ** 2

array([[1, 0],
       [0, 1]])

Element-wise binary operations require compatible shapes. Compare dimensions from right to left: each pair must be equal, or one must be 1; missing leading dimensions are treated as 1. This capability is called [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html):

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" alt="NumPy broadcasting diagram">

In [57]:
A = np.tile(np.arange(0, 40, 10), (3, 1)).T
A

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [58]:
A + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### 1.5 Other matrix operations

In [59]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [60]:
A.T # Transpose

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [61]:
np.linalg.det(A) # Determinant

np.float64(-2.9999999999999996)

In [62]:
np.linalg.matrix_rank(A) # Rank

np.int64(3)

In [63]:
np.diag(A) # Main diagonal

array([ 1,  5, 10])

In [64]:
B = np.linalg.inv(A) # Matrix inverse
B

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [65]:
A@B # unit matrix

array([[1.00000000e+00, 0.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00, 2.22044605e-16],
       [8.88178420e-16, 0.00000000e+00, 1.00000000e+00]])

In [66]:
np.sum((A@B - np.eye(3))**2) # Mismatch between elements.

np.float64(2.0830858278492343e-30)

Some functions have an `axis` parameter, which allows you to apply the function across different axes. When dealing with matrices, this typically means applying the function across rows or columns:


In [67]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [68]:
A.sum()

np.int64(46)


Some functions have an `axis` parameter that allows you to apply the function across different axes—in this case, across rows or columns.


In [69]:
np.sum(A, axis=1)  # Sum columns within each row: one total per row

array([ 6, 15, 25])

In [70]:
np.sum(A, axis=0)  # Sum rows within each column: one total per column

array([12, 15, 19])

In [71]:
A.sum(axis=0) # same

array([12, 15, 19])

# 2. Solving Problems

In the future, you will study data analysis. There, you will unexpectedly discover that many tabular datasets can be represented as a matrix. That's when you'll first witness the full power of NumPy.

### Task 1 (Maximum After Zero)

Implement a function that returns the maximum element in a vector $ x $ among the elements that are immediately preceded by a zero.

For example, for `x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`, the answer should be `5`. Return `None` if there are no eligible elements (for example, an empty vector, no zeros, or a single zero at the end). In `[0, 0]`, the second zero is eligible, so the answer is `0`.

__Why?__

You might be thinking, "Why? Can't we just use a loop?". Yes, you can. But vectorized computations can be much faster for large numeric arrays; the speedup depends on the operation, data size, and hardware. Often, it's much more convenient to use them than to write a loop.



In [72]:
import numpy as np

def max_after_zero(x):
    """
    Returns the maximum element in a vector x among the elements that are
    immediately preceded by a zero.

    Args:
        x (np.ndarray): The input vector.

    Returns:
        int or None: The maximum eligible element, or None if no such elements exist.
    """
    if x.size == 0:
        return None

    # Find indices where the element is zero
    zero_indices = np.where(x == 0)[0]

    eligible_elements = []
    for idx in zero_indices:
        # Check if there is an element immediately after the zero
        if idx + 1 < x.size:
            eligible_elements.append(x[idx + 1])

    if not eligible_elements:
        return None
    else:
        return np.max(eligible_elements)

# Example usage from the problem description:
x1 = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(f"x1: {x1}, Max after zero: {max_after_zero(x1)}")

x2 = np.array([0, 0])
print(f"x2: {x2}, Max after zero: {max_after_zero(x2)}")

x3 = np.array([1, 2, 3])
print(f"x3: {x3}, Max after zero: {max_after_zero(x3)}") # Expected: None

x4 = np.array([0])
print(f"x4: {x4}, Max after zero: {max_after_zero(x4)}")   # Expected: None

x5 = np.array([])
print(f"x5: {x5}, Max after zero: {max_after_zero(x5)}")   # Expected: None

x6 = np.array([0, 5])
print(f"x6: {x6}, Max after zero: {max_after_zero(x6)}")

x1: [6 2 0 3 0 0 5 7 0], Max after zero: 5
x2: [0 0], Max after zero: 0
x3: [1 2 3], Max after zero: None
x4: [0], Max after zero: None
x5: [], Max after zero: None
x6: [0 5], Max after zero: 5


### Task 2 (Normalization)

There is a matrix $ X $. You need to normalize its columns to the range $[0;1]$:

$$
x^{*} = \frac{x-\min(x)}{\max(x)-\min(x)}
$$

Compute the minimum and maximum separately for each column (`axis=0`). Assume finite numeric data and at least one row. For a constant column, set its normalized values to zero to avoid division by zero.

__Why?__

You might be wondering, "Why even do this?"

In machine learning, rows typically represent observations, and columns represent different features. Often, you need to compute distances between objects. Imagine that we have two observations in the dataset: Petya, who weighs $50$ kg and is $1$ meter tall, and Vasya, who weighs $75$ kg and is $1.5$ meters tall. In other words, Petya is represented by the vector  $(50, 1)$, and Vasya by $(75, 1.5)$.

If we need to compute the distance between them, we would do it like this:





In [73]:
print((50 - 75) ** 2)
print((1 - 1.5) ** 2)
squared_distance = (50 - 75) ** 2 + (1 - 1.5) ** 2
distance = np.sqrt(squared_distance)  # Euclidean distance
distance


625
0.25


np.float64(25.004999500099974)

Much more attention is paid to the weight. To avoid this, you need to normalize all features to the same scale, for example, to the range
$[0;1]$


### Task 3 (Closest Element in the Matrix)

Implement a function that takes a matrix $ X $ and a number $ a $ as inputs and returns the element in the matrix that is closest to the number $ a $. Then, rewrite the function so that it returns the element that is farthest from $ a $. Use absolute difference as the distance. Assume a nonempty matrix of finite real numbers; break ties by choosing the first element in row-major order.



In [74]:
import numpy as np

def closest_element_in_matrix(X, a):
    """
    Returns the element in matrix X that is closest to the number a.

    Args:
        X (np.ndarray): The input matrix.
        a (int or float): The target number.

    Returns:
        int or float: The element in X closest to a.
    """
    # Calculate the absolute difference for each element
    diff_matrix = np.abs(X - a)

    # Flatten the difference matrix and find the index of the minimum difference
    # np.argmin will return the first occurrence in case of ties
    min_diff_idx = np.argmin(diff_matrix.flatten())

    # Flatten the original matrix to retrieve the element at that index
    return X.flatten()[min_diff_idx]

def farthest_element_in_matrix(X, a):
    """
    Returns the element in matrix X that is farthest from the number a.

    Args:
        X (np.ndarray): The input matrix.
        a (int or float): The target number.

    Returns:
        int or float: The element in X farthest from a.
    """
    # Calculate the absolute difference for each element
    diff_matrix = np.abs(X - a)

    # Flatten the difference matrix and find the index of the maximum difference
    # np.argmax will return the first occurrence in case of ties
    max_diff_idx = np.argmax(diff_matrix.flatten())

    # Flatten the original matrix to retrieve the element at that index
    return X.flatten()[max_diff_idx]

# Example Usage:
X_example = np.array([
    [1, 5, 10],
    [2, 7, 12],
    [3, 8, 9]
])

num_a = 6

closest = closest_element_in_matrix(X_example, num_a)
farthest = farthest_element_in_matrix(X_example, num_a)

print(f"Matrix X:\n{X_example}")
print(f"Number a: {num_a}")
print(f"Closest element to {num_a}: {closest}") # Expected: 5 (diff 1), 7 (diff 1), 3 (diff 3)
print(f"Farthest element from {num_a}: {farthest}") # Expected: 12 (diff 6), 1 (diff 5)

X_tie = np.array([[-1, 1], [0, 0]])
num_b = 0
closest_tie = closest_element_in_matrix(X_tie, num_b)
farthest_tie = farthest_element_in_matrix(X_tie, num_b)
print(f"\nMatrix X_tie:\n{X_tie}")
print(f"Number b: {num_b}")
print(f"Closest element to {num_b} (with tie-breaking): {closest_tie}") # Expected: 0 (first 0)
print(f"Farthest element from {num_b} (with tie-breaking): {farthest_tie}") # Expected: -1 (first -1, diff 1)


Matrix X:
[[ 1  5 10]
 [ 2  7 12]
 [ 3  8  9]]
Number a: 6
Closest element to 6: 5
Farthest element from 6: 12

Matrix X_tie:
[[-1  1]
 [ 0  0]]
Number b: 0
Closest element to 0 (with tie-breaking): 0
Farthest element from 0 (with tie-breaking): -1


### Task 4 (Closest Row in the Matrix)

Let's make the previous task more challenging! Given a matrix $ X $ and a vector $ v $, find the row in matrix $ X $ that is closest to the vector $ v $ using Euclidean distance. Assume finite real values, at least one row, and `v.shape == (X.shape[1],)`. Return the first row in a tie.



In [75]:
import numpy as np

def closest_row_in_matrix(X, v):
    """
    Finds the row in matrix X that is closest to vector v using Euclidean distance.

    Args:
        X (np.ndarray): The input matrix (2D array).
        v (np.ndarray): The input vector (1D array) with shape (X.shape[1],).

    Returns:
        np.ndarray: The row from X that is closest to v.
    """
    # Calculate the difference between each row of X and the vector v.
    # Broadcasting handles subtracting v from each row of X.
    diffs = X - v

    # Calculate the Euclidean norm (distance) for each row of the differences.
    # axis=1 ensures the norm is calculated for each row, resulting in a 1D array of distances.
    distances = np.linalg.norm(diffs, axis=1)

    # Find the index of the minimum distance.
    # np.argmin returns the first index in case of ties, fulfilling the tie-breaking rule.
    closest_row_index = np.argmin(distances)

    # Return the closest row from the original matrix X
    return X[closest_row_index]

# Example Usage:
X_task4 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
v_task4 = np.array([3, 4, 5])

closest_row = closest_row_in_matrix(X_task4, v_task4)
print(f"Matrix X:\n{X_task4}")
print(f"Vector v: {v_task4}")
print(f"Closest row to v: {closest_row}") # Expected: [4, 5, 6]

# Another example with ties
X_ties = np.array([
    [1, 1],
    [0, 0],
    [2, 2]
])
v_ties = np.array([0.5, 0.5])

closest_row_ties = closest_row_in_matrix(X_ties, v_ties)
print(f"\nMatrix X with ties:\n{X_ties}")
print(f"Vector v with ties: {v_ties}")
print(f"Closest row to v (with tie-breaking): {closest_row_ties}") # Expected: [0, 0] (as it appears first in row-major order with same Euclidean distance as [1,1])

Matrix X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Vector v: [3 4 5]
Closest row to v: [4 5 6]

Matrix X with ties:
[[1 1]
 [0 0]
 [2 2]]
Vector v with ties: [0.5 0.5]
Closest row to v (with tie-breaking): [1 1]


__Why?__

Why would anyone need Tasks 3 and 4?! In machine learning, vectors are everywhere! For example, there's a magical technology called __word2vec__. In it, all words are transformed into vectors in such a way that the meaning of the word is encoded within the vector. As a result, you might unexpectedly discover that these vectors can be added and subtracted. If you take the vector for _king_, subtract _man_ from it, and add _woman_, you may get a vector close to _queen_. This is an illustrative analogy, not a guarantee; results depend on training data and the similarity measure (often cosine similarity).

All of these computations are conveniently done in `numpy` using the functions we've written.

More here in Stanford tutorial [numpy tutorial](https://cs231n.github.io/python-numpy-tutorial/)

# 3. Bonus Track: Linear Algebra

In this section of the notebook, we will take a deeper look at the functionality of the package. We will need the `numpy.linalg` module, which implements some applications of linear algebra.

## 3.1 Vector Norms

Let’s recall some norms that can be defined in the space $\mathbb{R}^{n}$ and see which libraries and functions can be used to compute them in `numpy`.

To compute various norms, we use the function `numpy.linalg.norm(x, ord=None, ...)`, where `x` is the input vector, and `ord` is the parameter that defines the norm (we will consider two possible values for it—1 and 2).

### $\ell_{2}$ Norm

The $\ell_{2}$ norm (also known as the Euclidean norm) for a vector $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ is computed by the formula:

$$
 \left\Vert x \right\Vert_{2} = \sqrt{\sum_{i=1}^n \left( x_{i} \right)^2}.
$$

In the function `numpy.linalg.norm(x, ord=None, ...)`, this corresponds to the parameter `ord=2`.


In [76]:
from numpy.linalg import norm

In [77]:
a = np.array([1, 2, -3])
norm(a, ord=2)

np.float64(3.7416573867739413)

### $\ell_{1}$ Norm

The $\ell_{1}$ norm (also known as the taxicab norm; it gives the [Manhattan distance](https://en.wikipedia.org/wiki/Taxicab_geometry) from the origin) for a vector $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ is computed by the formula:

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

In the function `numpy.linalg.norm(x, ord=None, ...)`, this corresponds to the parameter `ord=1`.

For more information on other norms (including matrix norms), see the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html).


In [78]:
a = np.array([1, 2, -3])
norm(a, ord=1)

np.float64(6.0)

## 3.2 Distances Between Vectors

For two vectors $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ and $y = (y_{1}, \dots, y_{n}) \in \mathbb{R}^{n}$, the $\ell_{1}$ and $\ell_{2}$ distances are computed by the following formulas, respectively:

$$
 \rho_{1}\left( x, y \right) = \left\Vert x - y \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} - y_{i} \right|
$$

$$
 \rho_{2}\left( x, y \right) = \left\Vert x - y \right\Vert_{2} =
 \sqrt{\sum_{i=1}^n \left( x_{i} - y_{i} \right)^2}.
$$


In [79]:
a = np.array([1, 2, -3])
b = np.array([-4, 3, 8])

In [80]:
norm(a - b, ord=1)

np.float64(17.0)

In [81]:
norm(a - b, ord=2)

np.float64(12.12435565298214)

The distance between vectors can also be calculated using the function `scipy.spatial.distance.cdist(XA, XB, metric='euclidean', **kwargs)` from the `scipy` module, which is designed for scientific and engineering computations.

In [82]:
from scipy.spatial.distance import cdist

The `scipy.spatial.distance.cdist(...)` function requires `XA` and `XB` to be exactly two-dimensional arrays with the same number of columns. For this reason, to use this function, it is necessary to convert the _vectors_ we are considering in this notebook into _row vectors_ using the methods we will discuss below.

The parameters `XA, XB` contain one observation per row. `metric` selects the distance measure; `p` is an extra parameter for the Minkowski metric (for more details on the metrics that can be used, see the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html)).

One way to convert a _vector_ into a _row vector (column vector)_ is to use the _method_ `array.reshape(shape)`, where the `shape` parameter specifies the vector's dimensions (a tuple of numbers).


In [83]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

print('Vector a:', a)
print('Its dimensions:', a.shape)
print('Vector b:', b)
print('Its dimensions:', b.shape)

a = a.reshape((1, 3))
b = b.reshape((1, 3))

print('After applying the reshape method:\n')
print('Row vector a:', a)
print('Its dimensions:', a.shape)
print('Row vector b:', b)
print('Its dimensions:', b.shape)

print('Manhattan distance between a and b (via cdist):', cdist(a, b, metric='cityblock'))


Vector a: [ 6  3 -5]
Its dimensions: (3,)
Vector b: [-1  0  7]
Its dimensions: (3,)
After applying the reshape method:

Row vector a: [[ 6  3 -5]]
Its dimensions: (1, 3)
Row vector b: [[-1  0  7]]
Its dimensions: (1, 3)
Manhattan distance between a and b (via cdist): [[22.]]


Note that after applying this method, the dimensions of the resulting row vectors will be equal to `shape`. Both `reshape` and the next method return a reshaped array without changing the original array’s shape; above, we reassigned the variable names `a` and `b`. In `numpy`, you can add dummy axes to the dimensions of objects using `np.newaxis`. To understand how to do this, let’s consider an example:


In [84]:
d = np.array([3, 0, 8, 9, -10])

print('Vector d:', d)
print('Its dimensions:', d.shape)

print('Vector d with newaxis --> row vector:\n', d[np.newaxis, :])
print('Resulting dimensions:', d[np.newaxis, :].shape)
print(' ')
print('Vector d with newaxis --> column vector:\n', d[:, np.newaxis])
print('Resulting dimensions:', d[:, np.newaxis].shape)


Vector d: [  3   0   8   9 -10]
Its dimensions: (5,)
Vector d with newaxis --> row vector:
 [[  3   0   8   9 -10]]
Resulting dimensions: (1, 5)
 
Vector d with newaxis --> column vector:
 [[  3]
 [  0]
 [  8]
 [  9]
 [-10]]
Resulting dimensions: (5, 1)


Importantly, `np.newaxis` adds an axis with a length of 1 to the dimensions (which makes sense because the number of elements must remain the same). Therefore, you should insert the new axis where you need a one in the dimension.

Now, let’s calculate the distances using `scipy.spatial.distance.cdist(...)`, using `np.newaxis` to transform the vectors:


In [85]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

print('Euclidean distance between a and b (via cdist):',
      cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean'))

Euclidean distance between a and b (via cdist): [[14.2126704]]


This function also allows you to calculate pairwise distances between sets of vectors. For example, suppose we have a matrix of size $m_{A} \times n$. We can think of it as a description of some $m_{A}$ observations in an $n$-dimensional space. Suppose we also have another similar matrix of size $m_{B} \times n$, where $m_{B}$ vectors exist in the same $n$-dimensional space. Often, it is necessary to calculate the pairwise distances between vectors from the first and second sets.

In this case, you can use the function `scipy.spatial.distance.cdist(XA, XB, metric='euclidean', **kwargs)`, where `XA` and `XB` are the two matrices described. The function returns a matrix of pairwise distances of size $m_{A} \times m_{B}$, where the element at position $[i, j]$ in the matrix is the distance between the $i$-th vector of the first set and the $j$-th vector of the second set.

`cdist` directly computes all cross-set pairwise distances. Compared with broadcasting differences and then applying `norm`, it avoids explicitly constructing an intermediate array of shape `(m_A, m_B, n)`.


## 3.3 Dot Product and Angle Between Vectors


In [86]:
a = np.array([0, 5, -1])
b = np.array([-4, 9, 3])


The dot product in the space $\mathbb{R}^{n}$ for two vectors $x = (x_{1}, \dots, x_{n})$ and $y = (y_{1}, \dots, y_{n})$ is defined as:

$$
\langle x, y \rangle = \sum_{i=1}^n x_{i} y_{i}.
$$
The dot product of two vectors can be computed using the `numpy.dot(a, b, ...)` function or the _method_ `vec1.dot(vec2)`, where `vec1` and `vec2` are the input vectors. These functions are also suitable for matrix multiplication, as demonstrated in Section 1.4.


In [87]:
np.dot(a, b)  # using the function
a.dot(b)      # using the method
a @ b         # using matrix multiplication


np.int64(42)

The length of a vector $x = (x_{1}, \dots, x_{n}) \in \mathbb{R}^{n}$ is defined as the square root of the dot product, which is equal to the Euclidean norm of the vector:
$$
\left| x \right| = \sqrt{\langle x, x \rangle} = \sqrt{\sum_{i=1}^n x_{i}^2} =  \left\Vert x \right\Vert_{2}.
$$
Now that we know the dot product of two non-zero vectors and their lengths, we can calculate the angle between them using the dot product:
$$
\langle x, y \rangle = \left| x \right| \left| y \right| \cos(\alpha)
\implies \cos(\alpha) = \frac{\langle x, y \rangle}{\left| x \right| \left| y \right|},
$$
where $\alpha \in [0, \pi]$ is the angle between the vectors $x$ and $y$.

For more details on how to compute the dot product in `numpy`, see the [documentation](https://numpy.org/doc/stable/reference/routines.linalg.html#matrix-and-vector-products).


In [88]:
cos_angle = np.dot(a, b) / norm(a) / norm(b)
cos_angle  # cosine

np.float64(0.8000362836474323)

In [89]:
np.arccos(np.clip(cos_angle, -1.0, 1.0))  # Angle in radians; clip floating-point roundoff


np.float64(0.6434406336093618)

## 3.4 Systems of Linear Equations

A __system of linear algebraic equations__ is a system of the form $Ax = b$, where $A \in \mathbb{R}^{n \times m}$, $x \in \mathbb{R}^{m \times 1}$, and $b \in \mathbb{R}^{n \times 1}$. In the case of a square non-singular matrix $A$, the solution to the system is unique.

In `numpy`, the solution to such a system can be found using the function `numpy.linalg.solve(a, b)`, where the first argument is the matrix $A$, and the second is the right-hand side $b$. In the example below, `b` has shape `(n,)`, so the solution also has shape `(n,)`; a column array of shape `(n, 1)` is also supported.



In [90]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

We can verify that the vector $x$ is indeed the solution of the system:

In [91]:
A.dot(x)

array([9., 8.])

There are cases when the system has no solution. However, we might still want to "solve" such a system. It seems logical to look for a vector $x$ that minimizes the expression $\left\Vert Ax - b\right\Vert^{2}$—this way, we approximate the expression $Ax$ to $b$.

In `numpy`, such a least-squares solution can be found using the function `numpy.linalg.lstsq(a, b, ...)`, where the first two arguments are the same as those for the function `numpy.linalg.solve()`.

In addition to the solution, the function returns three more values that we won't need right now.


In [92]:
A = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(A, b, rcond=None)

In [93]:
A

array([[0, 1],
       [1, 1],
       [2, 1],
       [3, 1]])

In [94]:
b

array([-1. ,  0.2,  0.9,  2.1])

In [95]:
x

array([ 1.  , -0.95])

## 3.5 Eigenvalues and Eigenvectors of a Matrix

For square matrices, the concepts of __eigenvector__ and __eigenvalue__ are defined.

Let $A$ be a square matrix where $A \in \mathbb{R}^{n \times n}$. An __eigenvector__ of the matrix $A$ is a non-zero vector $x \in \mathbb{C}^{n}$ such that for some $\lambda \in \mathbb{C}$, the equation $Ax = \lambda x$ holds. In this case, $\lambda$ is called an __eigenvalue__ of the matrix $A$. Eigenvalues and eigenvectors of a matrix play a significant role in linear algebra theory and its practical applications.

In `numpy`, the eigenvalues and eigenvectors of a matrix can be computed using the function `numpy.linalg.eig(a)`, where `a` is the input matrix. The function returns a one-dimensional array `v` of eigenvalues and a two-dimensional array `w` in which the columns represent the eigenvectors, so that the vector `w[:, i]` corresponds to the eigenvalue `v[i]`.


In [96]:
A = np.array([[2, 1], [1, 2]])
A


array([[2, 1],
       [1, 2]])

In [97]:
v, w = np.linalg.eig(A)
v  # Eigenvalues


array([3., 1.])

In [98]:
w  # Corresponding eigenvectors are the columns


array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [99]:
A @ w[:, 0]  # A times the first eigenvector


array([2.12132034, 2.12132034])

In [100]:
v[0] * w[:, 0]  # Eigenvalue times the same eigenvector


array([2.12132034, 2.12132034])

In [101]:
np.allclose(A @ w, w * v)  # Verify A w_i = v_i w_i for every column


True

__Note:__ For a real matrix, the eigenvalues or eigenvectors may be complex.


## 3.6 Complex Numbers in Python

__Complex numbers__ are numbers of the form $x + iy$, where $x$ and $y$ are real numbers, and $i$ is the imaginary unit (a value for which the equation $i^{2} = -1$ holds). The set of all complex numbers is denoted by the letter $\mathbb{C}$ (for more details on complex numbers, see [Wikipedia](https://en.wikipedia.org/wiki/Complex_number)).

In Python, complex numbers can be defined as follows ($j$ denotes the imaginary unit):


In [102]:
a = 3 + 2j
a

(3+2j)

In [103]:
b = 1j
b

1j

In [104]:
a * a

(5+12j)

In [105]:
a / (4 - 5j)

(0.0487804878048781+0.5609756097560976j)

In [106]:
np.abs(a)

np.float64(3.6055512754639896)

In [107]:
np.sqrt(3**2 + 2**2)

np.float64(3.605551275463989)